version: '2'

services:

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: galeb_api
    ports:
      - 3306:3306

  master:
    image: redis:3.2.6-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379