version: '2'

services:

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: galeb_api
    ports:
      - 3306:3306

  redis:
    image: redis:3.2.6-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
