version: '2'

services:

  ldap:
    image: tuxmonteiro/ldap-mock:latest
    ports:
      - 3890:3890

  redis:
    image: redis:3.2.6-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
