auth:
    localtoken: ${LOCAL_TOKEN:UNDEF}

api:
    url: ${GALEB_API_URL:http://127.0.0.1:8000}

ldap:
    url: ${GALEB_LDAP_URL:ldap://127.0.0.1:3890}
    userdn: ${GALEB_LDAP_USER:UNDEF}
    pass: ${GALEB_LDAP_PASS:UNDEF}
    base: ${GALEB_LDAP_BASE:UNDEF}

build:
    project: '@project.artifactId@'
    timestamp: '@timestamp@'
    version: '@project.version@'

endpoints:
    autoconfig:  { enabled: false }
    beans:       { enabled: false }
    configprops: { enabled: false }
    dump:        { enabled: false }
    env:         { enabled: false }
    health:      { enabled: true }
    info:        { enabled: true }
    mappings:    { enabled: false }
    metrics:     { enabled: false }
    shutdown:    { enabled: false }
    trace:       { enabled: false }

spring:
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        default-property-inclusion: non-empty
        deserialization: { use-big-decimal-for-floats: true }
        property-naming-strategy: SNAKE_CASE
        serialization: { write-dates-as-timestamps: false }

    main:
        banner-mode: 'off'

    redis:
        url: ${REDIS_URL:redis://127.0.0.1:6379}

    profiles:
        active: production

    session:
        store-type: REDIS

server:
    session:
        timeout: ${SESSION_TIMEOUT:1800}