/*
 * Copyright (c) 2014-2018 Globo.com - ATeam
 * All rights reserved.
 *
 * This source is subject to the Apache License, Version 2.0.
 * Please see the LICENSE file for more information.
 *
 * Authors: See AUTHORS file
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.galeb.core.entity;

public enum Role {
    ACCOUNT_CREATE,
    ACCOUNT_CREATE_ALL,
    ACCOUNT_UPDATE,
    ACCOUNT_UPDATE_ALL,
    ACCOUNT_DELETE,
    ACCOUNT_DELETE_ALL,
    ACCOUNT_VIEW,
    ACCOUNT_VIEW_ALL,

    BALANCEPOLICY_CREATE,
    BALANCEPOLICY_CREATE_ALL,
    BALANCEPOLICY_UPDATE,
    BALANCEPOLICY_UPDATE_ALL,
    BALANCEPOLICY_DELETE,
    BALANCEPOLICY_DELETE_ALL,
    BALANCEPOLICY_VIEW,
    BALANCEPOLICY_VIEW_ALL,

    ENVIRONMENT_CREATE,
    ENVIRONMENT_CREATE_ALL,
    ENVIRONMENT_UPDATE,
    ENVIRONMENT_UPDATE_ALL,
    ENVIRONMENT_DELETE,
    ENVIRONMENT_DELETE_ALL,
    ENVIRONMENT_VIEW,
    ENVIRONMENT_VIEW_ALL,

    HEALTHCHECK_CREATE,
    HEALTHCHECK_CREATE_ALL,
    HEALTHCHECK_UPDATE,
    HEALTHCHECK_UPDATE_ALL,
    HEALTHCHECK_DELETE,
    HEALTHCHECK_DELETE_ALL,
    HEALTHCHECK_VIEW,
    HEALTHCHECK_VIEW_ALL,

    HEALTHSTATUS_CREATE,
    HEALTHSTATUS_CREATE_ALL,
    HEALTHSTATUS_UPDATE,
    HEALTHSTATUS_UPDATE_ALL,
    HEALTHSTATUS_DELETE,
    HEALTHSTATUS_DELETE_ALL,
    HEALTHSTATUS_VIEW,
    HEALTHSTATUS_VIEW_ALL,

    POOL_CREATE,
    POOL_CREATE_ALL,
    POOL_UPDATE,
    POOL_UPDATE_ALL,
    POOL_DELETE,
    POOL_DELETE_ALL,
    POOL_VIEW,
    POOL_VIEW_ALL,

    PROJECT_CREATE,
    PROJECT_CREATE_ALL,
    PROJECT_UPDATE,
    PROJECT_UPDATE_ALL,
    PROJECT_DELETE,
    PROJECT_DELETE_ALL,
    PROJECT_VIEW,
    PROJECT_VIEW_ALL,

    ROLEGROUP_CREATE,
    ROLEGROUP_CREATE_ALL,
    ROLEGROUP_UPDATE,
    ROLEGROUP_UPDATE_ALL,
    ROLEGROUP_DELETE,
    ROLEGROUP_DELETE_ALL,
    ROLEGROUP_VIEW,
    ROLEGROUP_VIEW_ALL,

    RULE_CREATE,
    RULE_CREATE_ALL,
    RULE_UPDATE,
    RULE_UPDATE_ALL,
    RULE_DELETE,
    RULE_DELETE_ALL,
    RULE_VIEW,
    RULE_VIEW_ALL,

    RULEORDERED_CREATE,
    RULEORDERED_CREATE_ALL,
    RULEORDERED_UPDATE,
    RULEORDERED_UPDATE_ALL,
    RULEORDERED_DELETE,
    RULEORDERED_DELETE_ALL,
    RULEORDERED_VIEW,
    RULEORDERED_VIEW_ALL,

    TARGET_CREATE,
    TARGET_CREATE_ALL,
    TARGET_UPDATE,
    TARGET_UPDATE_ALL,
    TARGET_DELETE,
    TARGET_DELETE_ALL,
    TARGET_VIEW,
    TARGET_VIEW_ALL,

    TEAM_CREATE,
    TEAM_CREATE_ALL,
    TEAM_UPDATE,
    TEAM_UPDATE_ALL,
    TEAM_DELETE,
    TEAM_DELETE_ALL,
    TEAM_VIEW,
    TEAM_VIEW_ALL,

    VIRTUALHOST_CREATE,
    VIRTUALHOST_CREATE_ALL,
    VIRTUALHOST_UPDATE,
    VIRTUALHOST_UPDATE_ALL,
    VIRTUALHOST_DELETE,
    VIRTUALHOST_DELETE_ALL,
    VIRTUALHOST_VIEW,
    VIRTUALHOST_VIEW_ALL,

    VIRTUALHOSTGROUP_CREATE,
    VIRTUALHOSTGROUP_CREATE_ALL,
    VIRTUALHOSTGROUP_UPDATE,
    VIRTUALHOSTGROUP_UPDATE_ALL,
    VIRTUALHOSTGROUP_DELETE,
    VIRTUALHOSTGROUP_DELETE_ALL,
    VIRTUALHOSTGROUP_VIEW,
    VIRTUALHOSTGROUP_VIEW_ALL
}
