/*
 * Copyright (c) 2014-2018 Globo.com - ATeam
 * All rights reserved.
 *
 * This source is subject to the Apache License, Version 2.0.
 * Please see the LICENSE file for more information.
 *
 * Authors: See AUTHORS file
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.galeb.core.entity;

public enum Role {
    ADMIN,

    ACCOUNT_SAVE,
    ACCOUNT_SAVE_ALL,
    ACCOUNT_DELETE,
    ACCOUNT_DELETE_ALL,
    ACCOUNT_VIEW,
    ACCOUNT_VIEW_ALL,
    ACCOUNT_ADMIN,

    BALANCEPOLICY_SAVE,
    BALANCEPOLICY_SAVE_ALL,
    BALANCEPOLICY_DELETE,
    BALANCEPOLICY_DELETE_ALL,
    BALANCEPOLICY_VIEW,
    BALANCEPOLICY_VIEW_ALL,
    BALANCEPOLICY_ADMIN,

    ENVIRONMENT_SAVE,
    ENVIRONMENT_SAVE_ALL,
    ENVIRONMENT_DELETE,
    ENVIRONMENT_DELETE_ALL,
    ENVIRONMENT_VIEW,
    ENVIRONMENT_VIEW_ALL,
    ENVIRONMENT_ADMIN,

    HEALTHCHECK_SAVE,
    HEALTHCHECK_SAVE_ALL,
    HEALTHCHECK_DELETE,
    HEALTHCHECK_DELETE_ALL,
    HEALTHCHECK_VIEW,
    HEALTHCHECK_VIEW_ALL,
    HEALTHCHECK_ADMIN,

    HEALTHSTATUS_SAVE,
    HEALTHSTATUS_SAVE_ALL,
    HEALTHSTATUS_DELETE,
    HEALTHSTATUS_DELETE_ALL,
    HEALTHSTATUS_VIEW,
    HEALTHSTATUS_VIEW_ALL,
    HEALTHSTATUS_ADMIN,

    POOL_SAVE,
    POOL_SAVE_ALL,
    POOL_DELETE,
    POOL_DELETE_ALL,
    POOL_VIEW,
    POOL_VIEW_ALL,
    POOL_ADMIN,

    PROJECT_SAVE,
    PROJECT_SAVE_ALL,
    PROJECT_DELETE,
    PROJECT_DELETE_ALL,
    PROJECT_VIEW,
    PROJECT_VIEW_ALL,
    PROJECT_ADMIN,

    ROLEGROUP_SAVE,
    ROLEGROUP_SAVE_ALL,
    ROLEGROUP_DELETE,
    ROLEGROUP_DELETE_ALL,
    ROLEGROUP_VIEW,
    ROLEGROUP_VIEW_ALL,
    ROLEGROUP_ADMIN,

    RULE_SAVE,
    RULE_SAVE_ALL,
    RULE_DELETE,
    RULE_DELETE_ALL,
    RULE_VIEW,
    RULE_VIEW_ALL,
    RULE_ADMIN,

    RULEORDERED_SAVE,
    RULEORDERED_SAVE_ALL,
    RULEORDERED_DELETE,
    RULEORDERED_DELETE_ALL,
    RULEORDERED_VIEW,
    RULEORDERED_VIEW_ALL,
    RULEORDERED_ADMIN,

    TARGET_SAVE,
    TARGET_SAVE_ALL,
    TARGET_DELETE,
    TARGET_DELETE_ALL,
    TARGET_VIEW,
    TARGET_VIEW_ALL,
    TARGET_ADMIN,

    TEAM_SAVE,
    TEAM_SAVE_ALL,
    TEAM_DELETE,
    TEAM_DELETE_ALL,
    TEAM_VIEW,
    TEAM_VIEW_ALL,
    TEAM_ADMIN,

    VIRTUALHOST_SAVE,
    VIRTUALHOST_SAVE_ALL,
    VIRTUALHOST_DELETE,
    VIRTUALHOST_DELETE_ALL,
    VIRTUALHOST_VIEW,
    VIRTUALHOST_VIEW_ALL,
    VIRTUALHOST_ADMIN,

    VIRTUALHOSTGROUP_SAVE,
    VIRTUALHOSTGROUP_SAVE_ALL,
    VIRTUALHOSTGROUP_DELETE,
    VIRTUALHOSTGROUP_DELETE_ALL,
    VIRTUALHOSTGROUP_VIEW,
    VIRTUALHOSTGROUP_VIEW_ALL,
    VIRTUALHOSTGROUP_ADMIN
}
