version: '2'

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: galeb_api
    ports:
      - 3306:3306

  redis:
    image: redis:3.2.6-alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379

  ldap:
    image: tuxmonteiro/ldap-mock:latest
    container_name: ldap
    volumes:
      - "./users.json:/usr/src/app/users/users.json"
    ports:
      - 3890:3890

  broker:
    image: vromero/activemq-artemis:1.5.4
    container_name: broker
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USERNAME=guest
      - ARTEMIS_PASSWORD=guest
      - ARTEMIS_MIN_MEMORY=512M
      - ARTEMIS_MAX_MEMORY=1024M
      - ARTEMIS_PERF_JOURNAL=AUTO

  fake-oauth2:
    image: tuxmonteiro/galeb-fake-oauth2
    container_name: fake-oauth2
    ports:
      - 9000:9000
