#!/bin/bash
chmod 777 -R /opt/galeb/oldapi/logs || true
mkdir -p /opt/logs/galeb || true
ln -sf /opt/galeb/oldapi/logs /opt/logs/galeb/oldapi
ln -sf /opt/galeb/oldapi/lib/wrapper/bin/initscript /etc/init.d/galeb-oldapi
/usr/bin/systemctl enable galeb-oldapi || true
